# Generated by Django 3.0.3 on 2020-03-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_auto_20200308_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
