# Generated by Django 3.0.3 on 2020-03-26 01:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_auto_20200325_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Docente'),
        ),
    ]
