# Generated by Django 3.0.3 on 2020-04-24 23:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension', '0004_auto_20200325_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='imagen'),
        ),
    ]
