# Generated by Django 3.0.3 on 2020-04-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0005_auto_20200424_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='user',
        ),
    ]
